const AllCountriesList = [
  { label: "Afghanistan", value: "AFG", dial_code: "93" },
  { label: "Åland Islands", value: "ALA", dial_code: "358" },
  { label: "Albania", value: "ALB", dial_code: "355" },
  { label: "Algeria", value: "DZA", dial_code: "213" },
  { label: "American Samoa", value: "ASM", dial_code: "1684" },
  { label: "Andorra", value: "AND", dial_code: "376" },
  { label: "Angola", value: "AGO", dial_code: "244" },
  { label: "Anguilla", value: "AIA", dial_code: "1264" },
  { label: "Antarctica", value: "ATA", dial_code: "672" },
  { label: "Antigua and Barbuda", value: "ATG", dial_code: "1268" },
  { label: "Argentina", value: "ARG", dial_code: "54" },
  { label: "Armenia", value: "ARM", dial_code: "374" },
  { label: "Aruba", value: "ABW", dial_code: "297" },
  { label: "Australia", value: "AUS", dial_code: "61" },
  { label: "Austria", value: "AUT", dial_code: "43" },
  { label: "Azerbaijan", value: "AZE", dial_code: "994" },
  { label: "Bahamas", value: "BHS", dial_code: "1242" },
  { label: "Bahrain", value: "BHR", dial_code: "973" },
  { label: "Bangladesh", value: "BGD", dial_code: "880" },
  { label: "Barbados", value: "BRB", dial_code: "1246" },
  { label: "Belarus", value: "BLR", dial_code: "375" },
  { label: "Belgium", value: "BEL", dial_code: "32" },
  { label: "Belize", value: "BLZ", dial_code: "501" },
  { label: "Benin", value: "BEN", dial_code: "229" },
  { label: "Bermuda", value: "BMU", dial_code: "1441" },
  { label: "Bhutan", value: "BTN", dial_code: "975" },
  { label: "Bolivia", value: "BOL", dial_code: "591" },
  { label: "Bonaire, Sint Eustatius and Saba", value: "BES", dial_code: "599" },
  { label: "Bosnia and Herzegovina", value: "BIH", dial_code: "387" },
  { label: "Botswana", value: "BWA", dial_code: "267" },
  { label: "Bouvet Island", value: "BVT", dial_code: "47" },
  { label: "Brazil", value: "BRA", dial_code: "55" },
  { label: "British Indian Ocean Territory", value: "IOT", dial_code: "246" },
  { label: "Brunei Darussalam", value: "BRN", dial_code: "673" },
  { label: "Bulgaria", value: "BGR", dial_code: "359" },
  { label: "Burkina Faso", value: "BFA", dial_code: "226" },
  { label: "Burundi", value: "BDI", dial_code: "257" },
  { label: "Cambodia", value: "KHM", dial_code: "855" },
  { label: "Cameroon", value: "CMR", dial_code: "237" },
  { label: "Canada", value: "CAN", dial_code: "1" },
  { label: "Cape Verde", value: "CPV", dial_code: "238" },
  { label: "Cayman Islands", value: "CYM", dial_code: " 345" },
  { label: "Central African Republic", value: "CAF", dial_code: "236" },
  { label: "Chad", value: "TCD", dial_code: "235" },
  { label: "Chile", value: "CHL", dial_code: "56" },
  { label: "China", value: "CHN", dial_code: "86" },
  { label: "Christmas Island", value: "CXR", dial_code: "61" },
  { label: "Cocos (Keeling) Islands", value: "CCK", dial_code: "672" },
  { label: "Colombia", value: "COL", dial_code: "57" },
  { label: "Comoros", value: "COM", dial_code: "269" },
  { label: "Congo", value: "COG", dial_code: "242" },
  {
    label: "Congo, The Democratic Republic of the",
    value: "COD",
    dial_code: "243",
  },
  { label: "Cook Islands", value: "COK", dial_code: "682" },
  { label: "Costa Rica", value: "CRI", dial_code: "506" },
  { label: "Cote d'Ivoire", value: "CIV", dial_code: "225" },
  { label: "Croatia", value: "HRV", dial_code: "385" },
  { label: "Cuba", value: "CUB", dial_code: "53" },
  { label: "Curacao", value: "CUW", dial_code: "599" },
  { label: "Cyprus", value: "CYP", dial_code: "357" },
  { label: "Czech Republic", value: "CZE", dial_code: "420" },
  { label: "Denmark", value: "DNK", dial_code: "45" },
  { label: "Djibouti", value: "DJI", dial_code: "253" },
  { label: "Dominica", value: "DMA", dial_code: "1767" },
  { label: "Dominican Republic", value: "DOM", dial_code: "1809" },
  { label: "Ecuador", value: "ECU", dial_code: "593" },
  { label: "Egypt", value: "EGY", dial_code: "20" },
  { label: "El Salvador", value: "SLV", dial_code: "503" },
  { label: "Equatorial Guinea", value: "GNQ", dial_code: "240" },
  { label: "Eritrea", value: "ERI", dial_code: "291" },
  { label: "Estonia", value: "EST", dial_code: "372" },
  { label: "Ethiopia", value: "ETH", dial_code: "251" },
  { label: "Falkland Islands (Malvinas)", value: "FLK", dial_code: "500" },
  { label: "Faroe Islands", value: "FRO", dial_code: "298" },
  { label: "Fiji", value: "FJI", dial_code: "679" },
  { label: "Finland", value: "FIN", dial_code: "358" },
  { label: "France", value: "FRA", dial_code: "33" },
  { label: "French Guiana", value: "GUF", dial_code: "594" },
  { label: "French Polynesia", value: "PYF", dial_code: "689" },
  { label: "French Southern Territories", value: "ATF", dial_code: "262" },
  { label: "Gabon", value: "GAB", dial_code: "241" },
  { label: "Gambia", value: "GMB", dial_code: "220" },
  { label: "Georgia", value: "GEO", dial_code: "995" },
  { label: "Germany", value: "DEU", dial_code: "49" },
  { label: "Ghana", value: "GHA", dial_code: "233" },
  { label: "Gibraltar", value: "GIB", dial_code: "350" },
  { label: "Greece", value: "GRC", dial_code: "30" },
  { label: "Greenland", value: "GRL", dial_code: "299" },
  { label: "Grenada", value: "GRD", dial_code: "1473" },
  { label: "Guadeloupe", value: "GLP", dial_code: "590" },
  { label: "Guam", value: "GUM", dial_code: "1671" },
  { label: "Guatemala", value: "GTM", dial_code: "502" },
  { label: "Guernsey", value: "GGY", dial_code: "44" },
  { label: "Guinea", value: "GIN", dial_code: "224" },
  { label: "Guinea-Bissau", value: "GNB", dial_code: "245" },
  { label: "Guyana", value: "GUY", dial_code: "592" },
  { label: "Haiti", value: "HTI", dial_code: "509" },
  { label: "Heard Island and McDonald Islands", value: "HMD", dial_code: "672" },
  { label: "Holy See (Vatican City State)", value: "VAT", dial_code: "39" },
  { label: "Honduras", value: "HND", dial_code: "504" },
  { label: "Hong Kong", value: "HKG", dial_code: "852" },
  { label: "Hungary", value: "HUN", dial_code: "36" },
  { label: "Iceland", value: "ISL", dial_code: "354" },
  { label: "India", value: "IND", dial_code: "91" },
  { label: "Indonesia", value: "IDN", dial_code: "62" },
  { label: "Iran, Islamic Republic of", value: "IRN", dial_code: "98" },
  { label: "Iraq", value: "IRQ", dial_code: "964" },
  { label: "Ireland", value: "IRL", dial_code: "353" },
  { label: "Isle of Man", value: "IMN", dial_code: "44" },
  { label: "Israel", value: "ISR", dial_code: "972" },
  { label: "Italy", value: "ITA", dial_code: "39" },
  { label: "Jamaica", value: "JAM", dial_code: "1876" },
  { label: "Japan", value: "JPN", dial_code: "81" },
  { label: "Jersey", value: "JEY", dial_code: "44" },
  { label: "Jordan", value: "JOR", dial_code: "962" },
  { label: "Kazakhstan", value: "KAZ", dial_code: "7" },
  { label: "Kenya", value: "KEN", dial_code: "254" },
  { label: "Kiribati", value: "KIR", dial_code: "686" },
  {
    label: "Korea, Democratic People's Republic of",
    value: "PRK",
    dial_code: "850",
  },
  { label: "Korea, Republic of", value: "KOR", dial_code: "82" },
  { label: "Kuwait", value: "KWT", dial_code: "965" },
  { label: "Kyrgyzstan", value: "KGZ", dial_code: "996" },
  { label: "Lao People's Democratic Republic", value: "LAO", dial_code: "856" },
  { label: "Latvia", value: "LVA", dial_code: "371" },
  { label: "Lebanon", value: "LBN", dial_code: "961" },
  { label: "Lesotho", value: "LSO", dial_code: "266" },
  { label: "Liberia", value: "LBR", dial_code: "231" },
  { label: "Libya", value: "LBY", dial_code: "218" },
  { label: "Liechtenstein", value: "LIE", dial_code: "423" },
  { label: "Lithuania", value: "LTU", dial_code: "370" },
  { label: "Luxembourg", value: "LUX", dial_code: "352" },
  { label: "Macao", value: "MAC", dial_code: "853" },
  {
    label: "Macedonia, the Former Yugoslav Republic of",
    value: "MKD",
    dial_code: "389",
  },
  { label: "Madagascar", value: "MDG", dial_code: "261" },
  { label: "Malawi", value: "MWI", dial_code: "265" },
  { label: "Malaysia", value: "MYS", dial_code: "60" },
  { label: "Maldives", value: "MDV", dial_code: "960" },
  { label: "Mali", value: "MLI", dial_code: "223" },
  { label: "Malta", value: "MLT", dial_code: "356" },
  { label: "Marshall Islands", value: "MHL", dial_code: "692" },
  { label: "Martinique", value: "MTQ", dial_code: "596" },
  { label: "Mauritania", value: "MRT", dial_code: "222" },
  { label: "Mauritius", value: "MUS", dial_code: "230" },
  { label: "Mayotte", value: "MYT", dial_code: "262" },
  { label: "Mexico", value: "MEX", dial_code: "52" },
  { label: "Micronesia, Federated States of", value: "FSM", dial_code: "691" },
  { label: "Moldova, Republic of", value: "MDA", dial_code: "373" },
  { label: "Monaco", value: "MCO", dial_code: "377" },
  { label: "Mongolia", value: "MNG", dial_code: "976" },
  { label: "Montenegro", value: "MNE", dial_code: "382" },
  { label: "Montserrat", value: "MSR", dial_code: "1664" },
  { label: "Morocco", value: "MAR", dial_code: "212" },
  { label: "Mozambique", value: "MOZ", dial_code: "258" },
  { label: "Myanmar", value: "MMR", dial_code: "95" },
  { label: "Namibia", value: "NAM", dial_code: "264" },
  { label: "Nauru", value: "NRU", dial_code: "674" },
  { label: "Nepal", value: "NPL", dial_code: "977" },
  { label: "Netherlands", value: "NLD", dial_code: "31" },
  { label: "New Caledonia", value: "NCL", dial_code: "687" },
  { label: "New Zealand", value: "NZL", dial_code: "64" },
  { label: "Nicaragua", value: "NIC", dial_code: "505" },
  { label: "Niger", value: "NER", dial_code: "227" },
  { label: "Nigeria", value: "NGA", dial_code: "234" },
  { label: "Niue", value: "NIU", dial_code: "683" },
  { label: "Norfolk Island", value: "NFK", dial_code: "672" },
  { label: "Northern Mariana Islands", value: "MNP", dial_code: "1670" },
  { label: "Norway", value: "NOR", dial_code: "47" },
  { label: "Oman", value: "OMN", dial_code: "968" },
  { label: "Pakistan", value: "PAK", dial_code: "92" },
  { label: "Palau", value: "PLW", dial_code: "680" },
  { label: "Palestine, State of", value: "PSE", dial_code: "970" },
  { label: "Panama", value: "PAN", dial_code: "507" },
  { label: "Papua New Guinea", value: "PNG", dial_code: "675" },
  { label: "Paraguay", value: "PRY", dial_code: "595" },
  { label: "Peru", value: "PER", dial_code: "51" },
  { label: "Philippines", value: "PHL", dial_code: "63" },
  { label: "Pitcairn", value: "PCN", dial_code: "64" },
  { label: "Poland", value: "POL", dial_code: "48" },
  { label: "Portugal", value: "PRT", dial_code: "351" },
  { label: "Puerto Rico", value: "PRI", dial_code: "1" },
  { label: "Qatar", value: "QAT", dial_code: "974" },
  { label: "Reunion", value: "REU", dial_code: "262" },
  { label: "Romania", value: "ROU", dial_code: "40" },
  { label: "Russian Federation", value: "RUS", dial_code: "7" },
  { label: "Rwanda", value: "RWA", dial_code: "250" },
  { label: "Saint Barthélemy", value: "BLM", dial_code: "590" },
  {
    label: "Saint Helena, Ascension and Tristan da Cunha",
    value: "SHN",
    dial_code: "290",
  },
  { label: "Saint Kitts and Nevis", value: "KNA", dial_code: "1869" },
  { label: "Saint Lucia", value: "LCA", dial_code: "1758" },
  { label: "Saint Martin (French part)", value: "MAF", dial_code: "590" },
  { label: "Saint Pierre and Miquelon", value: "SPM", dial_code: "508" },
  { label: "Saint Vincent and the Grenadines", value: "VCT", dial_code: "1784" },
  { label: "Samoa", value: "WSM", dial_code: "685" },
  { label: "San Marino", value: "SMR", dial_code: "378" },
  { label: "Sao Tome and Principe", value: "STP", dial_code: "239" },
  { label: "Saudi Arabia", value: "SAU", dial_code: "966" },
  { label: "Senegal", value: "SEN", dial_code: "221" },
  { label: "Serbia", value: "SRB", dial_code: "381" },
  { label: "Seychelles", value: "SYC", dial_code: "248" },
  { label: "Sierra Leone", value: "SLE", dial_code: "232" },
  { label: "Singapore", value: "SGP", dial_code: "65" },
  { label: "Sint Maarten (Dutch part)", value: "SXM", dial_code: "1721" },
  { label: "Slovakia", value: "SVK", dial_code: "421" },
  { label: "Slovenia", value: "SVN", dial_code: "386" },
  { label: "Solomon Islands", value: "SLB", dial_code: "677" },
  { label: "Somalia", value: "SOM", dial_code: "252" },
  { label: "South Africa", value: "ZAF", dial_code: "27" },
  {
    label: "South Georgia and the South Sandwich Islands",
    value: "SGS",
    dial_code: "500",
  },
  { label: "South Sudan", value: "SSD", dial_code: "211" },
  { label: "Spain", value: "ESP", dial_code: "34" },
  { label: "Sri Lanka", value: "LKA", dial_code: "94" },
  { label: "Sudan", value: "SDN", dial_code: "249" },
  { label: "Surilabel", value: "SUR", dial_code: "597" },
  { label: "Svalbard and Jan Mayen", value: "SJM", dial_code: "47" },
  { label: "Swaziland", value: "SWZ", dial_code: "268" },
  { label: "Sweden", value: "SWE", dial_code: "46" },
  { label: "Switzerland", value: "CHE", dial_code: "41" },
  { label: "Syrian Arab Republic", value: "SYR", dial_code: "963" },
  { label: "Taiwan, Province of China", value: "TWN", dial_code: "886" },
  { label: "Tajikistan", value: "TJK", dial_code: "992" },
  { label: "Tanzania, United Republic of", value: "TZA", dial_code: "255" },
  { label: "Thailand", value: "THA", dial_code: "66" },
  { label: "Timor-Leste", value: "TLS", dial_code: "670" },
  { label: "Togo", value: "TGO", dial_code: "228" },
  { label: "Tokelau", value: "TKL", dial_code: "690" },
  { label: "Tonga", value: "TON", dial_code: "676" },
  { label: "Trinidad and Tobago", value: "TTO", dial_code: "1868" },
  { label: "Tunisia", value: "TUN", dial_code: "216" },
  { label: "Turkey", value: "TUR", dial_code: "90" },
  { label: "Turkmenistan", value: "TKM", dial_code: "993" },
  { label: "Turks and Caicos Islands", value: "TCA", dial_code: "1649" },
  { label: "Tuvalu", value: "TUV", dial_code: "688" },
  { label: "Uganda", value: "UGA", dial_code: "256" },
  { label: "Ukraine", value: "UKR", dial_code: "380" },
  { label: "United Arab Emirates", value: "ARE", dial_code: "971" },
  { label: "United Kingdom", value: "GBR", dial_code: "44" },
  { label: "United States", value: "USA", dial_code: "1" },
  { label: "United States Minor Outlying Islands", value: "UMI", dial_code: "1" },
  { label: "Uruguay", value: "URY", dial_code: "598" },
  { label: "Uzbekistan", value: "UZB", dial_code: "998" },
  { label: "Vanuatu", value: "VUT", dial_code: "678" },
  { label: "Venezuela, Bolivarian Republic of", value: "VEN", dial_code: "58" },
  { label: "Viet Nam", value: "VNM", dial_code: "84" },
  { label: "Virgin Islands, British", value: "VGB", dial_code: "1284" },
  { label: "Virgin Islands, U.S.", value: "VIR", dial_code: "1340" },
  { label: "Wallis and Futuna", value: "WLF", dial_code: "681" },
  { label: "Western Sahara", value: "ESH", dial_code: "212" },
  { label: "Yemen", value: "YEM", dial_code: "967" },
  { label: "Zambia", value: "ZMB", dial_code: "260" },
  { label: "Zimbabwe", value: "ZWE", dial_code: "263" },
];

export default AllCountriesList;
